data:
  data_path: drw_crypto # dir path

model:
  batch_size: 32
  #window_size: 31
  feature_number: 1000
  N: 6
  d_model_Encoder: 1000
  d_model_Decoder: 1000
  d_ff_Encoder: 2048
  d_ff_Decoder: 64
  h: 10
  dropout: 0.0
  local_context_length: 3
  device: cpu #cuda

train:
  lr: 1e-5
  epochs: 100