data:
  data_path: drw_crypto # dir path

model:
  batch_size: 32
  coin_num: 32
  window_size: 31
  feature_number: 875
  N: 6
  d_model_Encoder: 512
  d_model_Decoder: 16
  d_ff_Encoder: 2048
  d_ff_Decoder: 64
  h: 8
  dropout: 0.0
  local_context_length: 3
  device: cpu #cuda