data:
  data_path: drw_crypto # dir path

model:
  batch_size: 64
  window_size: 32
  feature_number: 874
  N: 1
  d_model_Encoder: 874
  d_model_Decoder: 874
  d_ff_Encoder: 2048
  d_ff_Decoder: 64
  h: 2
  dropout: 0.0
  local_context_length: 4
  device: mps #cuda

train:
  lr: 1e-5
  epochs: 10