data:
  data_path: drw_crypto # dir path

model:
  batch_size: 128
  window_size: 128
  feature_number: 100
  N: 3
  d_model_Encoder: 100
  d_model_Decoder: 100
  d_ff_Encoder: 512
  d_ff_Decoder: 64
  h: 5
  dropout: 0.2
  local_context_length: 12
  device: cuda

train:
  lr: 1e-6
  epochs: 10
  optimizer:
    learning_rate: 5.0e-5
    weight_decay: 1.0e-7
    t_initial: 10000
    warmup_t: 5000 #20000

logger:
  type: tensorboard