lr: 0.001
model_config:
  N: 1
  batch_size: 128
  d_ff_Decoder: 64
  d_ff_Encoder: 2048
  d_model_Decoder: 874
  d_model_Encoder: 874
  device: cpu
  dropout: 0.0
  feature_number: 874
  h: 2
  local_context_length: 4
